"""Abandone all hope, sqlmodel

Revision ID: 8041313f5c10
Revises: a4cf35771e54
Create Date: 2022-03-03 21:37:19.902592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8041313f5c10"
down_revision = "a4cf35771e54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended", sa.DateTime(timezone=True), nullable=True),
        sa.Column("added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reviewed_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("time_taken", sa.Float(), nullable=True),
        sa.Column(
            "other_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("review_session_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_session_id"],
            ["review_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("reviewedcard")
    op.drop_table("reviewsession")
    op.add_column("card", sa.Column("deck_id", sa.Integer(), nullable=True))
    op.alter_column("card", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("card", "prompt", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("card", "answer", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("card", "card_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "card", "added", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.create_foreign_key(None, "card", "deck", ["deck_id"], ["id"])
    op.alter_column("deck", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "deck", "added", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "deck", "added", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("deck", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint(None, "card", type_="foreignkey")
    op.alter_column(
        "card", "added", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("card", "card_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("card", "answer", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("card", "prompt", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("card", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("card", "deck_id")
    op.create_table(
        "reviewsession",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "started", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("ended", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="reviewsession_pkey"),
    )
    op.create_table(
        "reviewedcard",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "review_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("correct", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "time_taken",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "other_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="reviewedcard_pkey"),
    )
    op.drop_table("reviewed_card")
    op.drop_table("review_session")
    # ### end Alembic commands ###
