"""Init

Revision ID: a4cf35771e54
Revises: 
Create Date: 2022-03-02 21:01:52.524400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy.dialects.postgresql as pg

# revision identifiers, used by Alembic.
revision = 'a4cf35771e54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewedcard',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.Column('other_metrics', pg.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewsession',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewsession')
    op.drop_table('reviewedcard')
    op.drop_table('deck')
    op.drop_table('card')
    # ### end Alembic commands ###
