# Generated by Django 4.0 on 2021-12-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kards', '0006_rename_cardreviewed_reviewedcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewedcard',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewedcard',
            name='other_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
